build:
  image: 
    name: node:16-alpine
    entrypoint: [""]
  script:
    - git clone 
upload to s3:
  image:
    name: banst/awscli
    entrypoint: [""]
  script:
    - aws configure set region us-east-1
    - touch foo.txt
    - aws s3 cp foo.txt s3://$S3_BUCKET/foo.txt